### ISSUE TITLE
Currently mutations are required... make them not required

### ISSUE THREAD

**Issue by jakelacey2012** [RedLeap/GraphQL#8]
```javascript
 gql-submodules   ./src/data/modules/SWAPI/config.yml, Seen... +0ms
  gql-submodules       Each config... +7ms
  gql-submodules          Starwars is active. +1ms
/Users/jakelacey/workspace/proj/yt/tmp/GraphQL/node_modules/graphql/jsutils/invariant.js:19
    throw new Error(message);
    ^

Error: Mutation fields must be an object with field names as keys or a function which returns such an object.
    at invariant (/Users/jakelacey/workspace/proj/yt/tmp/GraphQL/node_modules/graphql/jsutils/invariant.js:19:11)
    at defineFieldMap (/Users/jakelacey/workspace/proj/yt/tmp/GraphQL/node_modules/graphql/type/definition.js:315:27)
    at GraphQLObjectType.getFields (/Users/jakelacey/workspace/proj/yt/tmp/GraphQL/node_modules/graphql/type/definition.js:276:44)
    at /Users/jakelacey/workspace/proj/yt/tmp/GraphQL/node_modules/graphql/type/schema.js:207:27
    at typeMapReducer (/Users/jakelacey/workspace/proj/yt/tmp/GraphQL/node_modules/graphql/type/schema.js:219:7)
    at Array.reduce (native)
    at new GraphQLSchema (/Users/jakelacey/workspace/proj/yt/tmp/GraphQL/node_modules/graphql/type/schema.js:95:34)
    at Object.buildASTSchema (/Users/jakelacey/workspace/proj/yt/tmp/GraphQL/node_modules/graphql/utilities/buildASTSchema.js:205:10)
    at buildSchemaFromTypeDefinitions (/Users/jakelacey/workspace/proj/yt/tmp/GraphQL/node_modules/graphql-tools/src/schemaGenerator.ts:146:31)
    at _generateSchema (/Users/jakelacey/workspace/proj/yt/tmp/GraphQL/node_modules/graphql-tools/src/schemaGenerator.ts:72:18)
```

**Comment by jakelacey2012** [comment]
Fix in e223e2c
